EQUIPMENT_ID = "EXCAVATOR_01"

EVENT_NAME = "WORKER_NEAR_MOVING_EXCAVATOR"

PROXIMITY_MARGIN_RATIO = 0.35

ENTER_CONFIRM_FRAMES = 2

DEFAULT_EQUIPMENT_STATE = "STOP"  # RUNNING / STOP

LOG_PATH = "vision_events.csv"

MOTION_START_THRESHOLD = 0.055
MOTION_STOP_THRESHOLD = 0.022
MOTION_PIXEL_THRESHOLD = 18
MOTION_START_FRAMES = 1
MOTION_STOP_FRAMES = 8
